import Head from 'next/head';
import React, { useContext } from 'react'
import { getSession, useSession } from 'next-auth/react'
import Header from '../../../components/Header';
import Sidebar from '../../../components/Sidebar';
import Sidebarr from '../../../components/Sidebarr';
import { AppContext } from '../../../contexts/AppContext';
import SinglePost from '../../../components/SinglePost';
import Modal from '../../../components/Modal';
import Login from '../../../components/Login';
const PostPage = () => {
    
  const { data: session } = useSession()
  const [appContext] = useContext(AppContext)
  if (!session) return <Login />

    return (
        <div>
             <Head>
        <title>Yaznbook - منشورات</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Yaznbook.jpg" />
      </Head>
      <main className='relative max-w-[1400px] mx-auto'>
  <Header />

        <Sidebar />
        <Sidebarr />

        <div className="flex gap-6" >
<SinglePost />
{appContext?.isModalOpen && <Modal />}
        </div>

    </main>
        </div>
    );
}



export default PostPage;

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session
    },
  };
}
