import Head from 'next/head';
import React, { useContext } from 'react'
import { getSession, useSession } from 'next-auth/react'
import Feed from '../../components/Feed'
import Login from '../../components/Login'
import Modal from '../../components/Modal'
import Sidebar from '../../components/Sidebar'
import Sidebarr from "../../components/Sidebarr"
import { AppContext } from '../../contexts/AppContext'
import Header from "../../components/Header"

 function Home() {
  const { data: session } = useSession()
  const [appContext] = useContext(AppContext)

  if (!session) return <Login />


  return (
    <>
      <Head>
        <title>Yaznbook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Yaznbook.jpg" />
      </Head>
      <main className="relative max-w-[1400px] mx-auto" >
     <Header />
     <Sidebar />
     <div className="flex gap-6" >
     <Feed />
     {appContext?.isModalOpen && <Modal />}
     </div>
     <Sidebarr />
      </main>
    </>
  )
}


export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}

export default Home;